### ISSUE TITLE
TERMINAL LOG 

### ISSUE THREAD

**Issue by emad2333** [Aditya20110/downr1n-gui#8] opened 2023-04-23 02:55 UTC
Last login: Fri Apr 21 18:05:08 on ttys000
aish@EMADs-MacBook-Air ~ % cd /Users/aish/Downloads/downr1n-gui-main 
aish@EMADs-MacBook-Air downr1n-gui-main % python3 ./downr1n-gui.py
Unable to create basic Accelerated OpenGL renderer.
Unable to create basic Accelerated OpenGL renderer.
Core Image is now using the software OpenGL renderer. This will be slow.
sudo ./downr1n.sh --downgrade 14.6
Password:
[*] Command ran: sudo ./downr1n.sh --downgrade 14.6
fatal: not a git repository (or any of the parent directories): .git

**Comment by Aditya20110** [comment] 2023-04-23 03:03
bro,please use git pull command or clone gui in some other directory

**Comment by emad2333** [comment] 2023-04-23 05:36
new error :

unable to receive message from FDR 

shall i retry

**Comment by Aditya20110** [comment] 2023-04-23 05:37
Beo which iphone u are using? Version?

**Comment by emad2333** [comment] 2023-04-23 05:38
iphone x A11 version 15.6 to 14.8

**Comment by Aditya20110** [comment] 2023-04-23 05:39
Bro ,try again, and send screenshots

**Comment by emad2333** [comment] 2023-04-23 05:40
right from beginning
or just boot option

**Comment by Aditya20110** [comment] 2023-04-23 05:41
Beginning

**Comment by emad2333** [comment] 2023-04-23 05:49
i think it s future restore error

**Comment by Aditya20110** [comment] 2023-04-23 05:51
Yeah,i will see ,but first send me screenshots

**Comment by emad2333** [comment] 2023-04-23 05:53
i will send you the log

**Comment by emad2333** [comment] 2023-04-23 05:54
which is easier cli or gui

**Comment by Aditya20110** [comment] 2023-04-23 05:55
Gui better,it will give you same error on cli. Pls dont ask me stupid questions

**Comment by emad2333** [comment] 2023-04-23 06:35
doing it again if it fails this time any quick fixes

**Comment by Aditya20110** [comment] 2023-04-23 06:38
actually this issue is caused by restore mode kernel being incompatible with restoresep

**Comment by Aditya20110** [comment] 2023-04-23 06:39
It's either because that user tried to restore to 14.2 (potential SEP incompatiblity) or it's something else unrelated to idevicerestore as many users succeeded restores on A10,

So see the sep and baseband chart for more guidance. And if any more doubts join my discord server im closing this issue

**Closed by Aditya20110** 2023-04-23 06:39 UTC

**Comment by emad2333** [comment] 2023-04-23 06:41
i restored to ios 14.8
